# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff7dfb65394665a65270d1380b6a66024f6679c8390f5be0d28e415125a7427f6b185db5123b0be8fbe7deeb9202aea28f84d4d0a1f64e2265226798307a073

test:
  secret_key_base: d5243c10066bf9ff3be4c8eff002a4b32e272d9f9d15597c089861b9d368ae74cd7068a3f0573f387fdf44ffc974cc2e0fee99354a0516864c56c4b306d5877f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
